### ISSUE TITLE
When timer is started again after a finished focus session, shows alert about finished session of length 0

### ISSUE THREAD

**Issue by ghost** [narlock/TamoStudy#8] opened 2021-07-29 15:19 UTC
After a focus session is finished, starting another one makes TamoStudy think that the length set is 0 and immediately finishes it:

![scrsht](https://user-images.githubusercontent.com/86888182/127505170-f4feec92-c8fc-4ac8-aeaa-0bf67b0ce3e9.png)

Swapping the time from the dropdown for a different one (and then back) seems to solve it, but only until the next session.
(This is on Linux, despite the Mac-like theme, just in case that makes a difference)

**Comment by narlock** [comment] 2021-07-29 19:47
Hey stayinside4ever,

Firstly I'd like to say that I'm glad you are using TamoStudy! It really means a lot to me and the future of this project.

In regards to your issue thread, I've actually coded it this way. (As in, it's not a bug or anything) I will though, rid the zero seconds as no one will study for zero seconds, and hopefully update the timer so if the user is on the 5-min increment the lowest possible session will be 5-min.

I could potentially also set up an automated session timer. for instance, if you selected 60 minutes for a session, when the session pop up is closed the time will go back to that 60 minutes (on the actual timer, without need for re-selection; although I believe it already worked like this? I can look into the solution)

As far as versions go, TamoStudy works the same no matter the operating system the user has.

Let me know your thoughts!

**Comment by stayinside4ever** [comment] 2021-07-30 07:23
Thanks, Anthony! It does seem like a cool project!

If it's not meant to be a bug - why choose to do it this way? Most users would use the app to study for more than one session of the same length in a row, presumably. It would make sense to reset the timer start values to the amount already selected in the dropdown after closing the session end alert, rather than let it sit at 0 until the time is re-selected (which is what I assume you meant by "automated session timer"?).

**Comment by narlock** [comment] 2021-10-09 14:14
It appears that the user that originally created this post is no longer a user on GitHub

This solution has been temporarily fixed: the fix is similar to if the use was just using the standard interval timer. The timer will reset back to zero, and the selected Index of the dropdown menu will return to it's original place - for the five-minute interval timer, this position is 05:00, however, the time will need to be set for the time being

Later, I will implement a solution in which the user can most likely choose how they want this setting to work, whether they want the timer to reset completely (consider, if they want to count their "break" time through TamoStudy as well, they would probably want to change it) instead of resetting it back to what they had originally.

This will close this issue thread.

**Closed by narlock** 2021-10-09 14:14 UTC
Labels: enhancement
